#!/bin/bash
url="$(git config --get remote.origin.url)"

while getopts "b" opt; do
  case ${opt} in
  b)
    branch=$(git branch | sed -n -e 's/^\* \(.*\)/\1/p')
    url="${url}/tree/${branch}"
    ;;
  esac
done
# branch=$(git branch | sed -n -e 's/^\* \(.*\)/\1/p')

if [ -z $url ]; then
  echo "There is no remote specified [or URL is null]"
else
  # url=${url/git@github.com:/https://www.github.com/}
  url=${url/.git//}
  # url="${url}/tree/${branch}"
  echo $url
  open $url
  # xdg-open echo ${url/git@github.com:/https://www.github.com/} # Does not work
fi
