#!/bin/bash
url="$(git config --get remote.origin.url)"
if [ -z $url ]; then
  echo "There is no remote specified [or URL is null]"
else
  url=${url/git@github.com:/https://www.github.com/}
  open $url
  # xdg-open echo ${url/git@github.com:/https://www.github.com/} # Does not work
fi
