#!/bin/bash
url="$(git config --get remote.origin.url)"
os=$(uname);
openCmd="open"
hostregex="(?<=@).+(?=:)"

# using ssh
git=$(echo $url | cut -c 1-3)
if [ $git = "git" ]; then
echo "transforming ssh url into http url.."
prefix="https://"
host=$(echo $url | grep -o -P '(?<=@).*(?=:)')
userrepo=$(cut -d ":" -f2 <<< "$url")
url="$prefix$host/$userrepo"
fi

if [ "$os" = "Linux" ]; then
openCmd="xdg-open"
fi

while getopts "bc:" opt; do
  case ${opt} in
  c)
    stem="commit/"
    commit=$OPTARG
    url="${url}${stem}${commit}"
    ;;
  b)
    branch=$(git branch | sed -n -e 's/^\* \(.*\)/\1/p')
    url="${url}/tree/${branch}"
    ;;
  esac
done
# branch=$(git branch | sed -n -e 's/^\* \(.*\)/\1/p')

if [ -z $url ]; then
  echo "There is no remote specified [or URL is null]"
else
  # url=${url/git@github.com:/https://www.github.com/}
  url=${url/.git//}
  # url="${url}/tree/${branch}"
  echo $url
  $openCmd $url
  # xdg-open echo ${url/git@github.com:/https://www.github.com/} # Does not work
fi
