#!/bin/bash
os=$(uname);
openCmd="open"
dobranch=false

if [ "$os" = "Linux" ]; then
openCmd="xdg-open"
fi
remote="origin"

while getopts "bc:a:r:" opt; do
  case ${opt} in
  r)
    remote=$OPTARG
    ;;
  c)
    commit=$OPTARG
    ;;
  b)
    dobranch=true
    ;;
  a) 
    if [ "$OPTARG" = "chrome" ]; then
    browser="chrome"
    fi 
    if [ "$OPTARG" = "brave" ]; then
    browser="Brave Browser"
    fi
    openCmd="$openCmd -a '$browser'"
    echo "Open Command: $openCmd"
    ;;
  esac
done


url="$(git config --get remote.$remote.url)"


if [ $dobranch = "true" ]; then
echo "Doing branch"
    branch=$(git branch | sed -n -e 's/^\* \(.*\)/\1/p')
    url="${url}tree/${branch}"
fi

# if [ $commit = "" ]; then
#     stem="commit/"
#     url="${url}${stem}${commit}"
# fi


# USING SSH
git=$(echo $url | cut -c 1-3)
if [ $git = "git" ]; then
echo "transforming ssh url into http url.."
prefix="https://"
host=$(echo $url | grep -o -P '(?<=@).*(?=:)')
userrepo=$(cut -d ":" -f2 <<< "$url")
url="$prefix$host/$userrepo"
fi
# END USING SSH




# branch=$(git branch | sed -n -e 's/^\* \(.*\)/\1/p')

if [ -z $url ]; then
  echo "There is no remote specified [or URL is null]"
else
  # url=${url/git@github.com:/https://www.github.com/}
  url=${url/.git//}
  # url="${url}/tree/${branch}"
  echo $url
  echo $openCmd
  echo "$openCmd $url"
  eval $openCmd $url
  # xdg-open echo ${url/git@github.com:/https://www.github.com/} # Does not work
fi
